[2022-12-10 20:48:34,005] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 20:48:43,864] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 20:48:43,864] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 20:48:43,864] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 20:49:27,404] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /modules 301 [0.01, 127.0.0.1:55534]
[2022-12-10 20:49:31,418] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [4.01, 127.0.0.1:55534]
[2022-12-10 20:49:32,368] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 304 [0.25, 127.0.0.1:55540]
[2022-12-10 20:49:32,375] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css 304 [0.25, 127.0.0.1:55534]
[2022-12-10 20:49:32,380] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/default.css 304 [0.24, 127.0.0.1:55542]
[2022-12-10 20:49:32,385] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/prettify.css 304 [0.24, 127.0.0.1:55541]
[2022-12-10 20:49:32,422] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/ajax-form.js 304 [0.28, 127.0.0.1:55544]
[2022-12-10 20:49:32,426] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 304 [0.28, 127.0.0.1:55543]
[2022-12-10 20:49:32,430] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/csrf.js 304 [0.06, 127.0.0.1:55540]
[2022-12-10 20:49:32,437] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/bootstrap.min.js 304 [0.04, 127.0.0.1:55534]
[2022-12-10 20:49:32,441] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/prettify-min.js 304 [0.04, 127.0.0.1:55542]
[2022-12-10 20:49:32,444] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/default.js 304 [0.04, 127.0.0.1:55541]
[2022-12-10 20:49:32,606] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/img/grid.png 304 [0.01, 127.0.0.1:55545]
[2022-12-10 20:49:32,731] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 304 [0.04, 127.0.0.1:55545]
[2022-12-10 20:49:33,112] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 20:49:33,113] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.22, 127.0.0.1:55545]
[2022-12-10 20:49:33,197] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-10 20:49:33,199] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.02, 127.0.0.1:55545]
[2022-12-10 20:50:22,748] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:55573]
[2022-12-10 20:50:23,035] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 20:50:23,036] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:55573]
[2022-12-10 20:50:31,428] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
[2022-12-10 20:50:31,449] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [0.56, 127.0.0.1:55582]
[2022-12-10 20:50:58,760] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:55606]
[2022-12-10 20:50:58,960] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 20:50:58,962] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:55606]
[2022-12-10 20:51:07,847] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 372, in post
    datas = json.loads(request.body.decode('utf-8'))
  File "D:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2022-12-10 20:51:07,857] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [0.22, 127.0.0.1:55614]
[2022-12-10 20:51:08,059] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 20:51:08,061] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:55614]
[2022-12-10 20:51:11,322] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:55614]
[2022-12-10 20:51:17,886] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:55625]
[2022-12-10 20:51:18,053] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 20:51:18,054] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:55625]
[2022-12-10 20:52:17,314] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 20:52:18,414] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 20:52:18,415] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 20:52:18,420] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 20:53:11,595] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
[2022-12-10 20:53:11,616] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [40.99, 127.0.0.1:55676]
[2022-12-10 20:59:13,425] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.54, 127.0.0.1:56127]
[2022-12-10 20:59:13,752] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 20:59:13,758] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.12, 127.0.0.1:56127]
[2022-12-10 21:00:43,792] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:00:44,244] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:00:44,244] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:00:44,244] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:00:58,662] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:00:59,076] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:00:59,076] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:00:59,076] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:01:04,689] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.73, 127.0.0.1:56247]
[2022-12-10 21:01:07,488] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:01:07,490] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.05, 127.0.0.1:56247]
[2022-12-10 21:01:14,704] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.11, 127.0.0.1:56255]
[2022-12-10 21:01:14,846] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:01:14,847] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:56255]
[2022-12-10 21:01:26,801] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.28, 127.0.0.1:56262]
[2022-12-10 21:02:01,142] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:02:01,548] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:02:01,548] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:02:01,548] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:02:12,500] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.21, 127.0.0.1:56300]
[2022-12-10 21:02:12,659] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:02:12,660] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:56300]
[2022-12-10 21:02:30,435] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
[2022-12-10 21:02:30,450] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [0.22, 127.0.0.1:56316]
[2022-12-10 21:02:30,831] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:02:30,833] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:56316]
[2022-12-10 21:02:47,584] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:56328]
[2022-12-10 21:02:47,737] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:02:47,741] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:56328]
[2022-12-10 21:03:03,018] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
[2022-12-10 21:03:03,026] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [0.21, 127.0.0.1:56339]
[2022-12-10 21:03:03,259] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:03:03,261] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.05, 127.0.0.1:56339]
[2022-12-10 21:03:05,485] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:56343]
[2022-12-10 21:03:05,659] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:03:05,661] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:56343]
[2022-12-10 21:05:42,188] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:05:45,497] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:06:59,237] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:07:02,156] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:07:54,951] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:07:57,886] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:08:16,627] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:08:19,582] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:09:06,515] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:09:06,874] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:09:06,889] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:09:06,889] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:09:10,817] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.20, 127.0.0.1:56557]
[2022-12-10 21:09:11,007] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:09:11,010] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:56557]
[2022-12-10 21:09:26,118] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.11, 127.0.0.1:56568]
[2022-12-10 21:09:26,312] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:09:26,313] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:56568]
[2022-12-10 21:09:54,433] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
[2022-12-10 21:09:54,445] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP POST /modules/ 500 [0.22, 127.0.0.1:56580]
[2022-12-10 21:09:54,658] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:09:54,661] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:56580]
[2022-12-10 21:10:19,247] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:56592]
[2022-12-10 21:10:19,459] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:10:19,462] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:56592]
[2022-12-10 21:11:36,255] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:11:36,707] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:11:36,707] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:11:36,723] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:11:39,470] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.21, 127.0.0.1:56641]
[2022-12-10 21:11:39,712] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:11:39,714] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.05, 127.0.0.1:56641]
[2022-12-10 21:13:43,945] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:13:46,972] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:13:47,428] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:13:47,429] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:13:47,432] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:13:50,751] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.39, 127.0.0.1:56706]
[2022-12-10 21:13:53,020] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:13:53,021] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:56706]
[2022-12-10 21:30:42,354] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:30:43,476] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:30:43,478] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:30:43,483] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:30:48,515] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.87, 127.0.0.1:57104]
[2022-12-10 21:30:51,211] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:30:51,215] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.12, 127.0.0.1:57109]
[2022-12-10 21:32:30,456] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:32:31,520] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:32:31,520] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:32:31,520] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:32:35,472] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.64, 127.0.0.1:57169]
[2022-12-10 21:32:35,920] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:32:35,925] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.12, 127.0.0.1:57173]
[2022-12-10 21:34:51,910] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:34:52,987] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:34:52,987] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:34:52,987] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:34:56,138] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.57, 127.0.0.1:57263]
[2022-12-10 21:34:58,964] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:34:58,968] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.11, 127.0.0.1:57263]
[2022-12-10 21:36:58,315] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:36:58,705] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:36:58,705] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:36:58,705] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:37:14,745] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:37:15,775] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:37:15,775] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:37:15,791] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:37:21,665] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.64, 127.0.0.1:57352]
[2022-12-10 21:37:22,056] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:37:22,062] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.11, 127.0.0.1:57352]
[2022-12-10 21:41:21,606] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:41:30,280] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-10 21:41:37,491] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:41:38,656] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:41:38,656] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:41:38,656] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:41:41,689] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.55, 127.0.0.1:57532]
[2022-12-10 21:41:44,184] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:41:44,188] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.10, 127.0.0.1:57532]
[2022-12-10 21:42:43,277] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:42:45,009] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:42:45,009] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:42:45,009] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:42:48,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.53, 127.0.0.1:57587]
[2022-12-10 21:42:49,242] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:42:49,247] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.12, 127.0.0.1:57587]
[2022-12-10 21:43:37,432] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:43:37,867] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:43:37,868] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:43:37,869] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:43:43,895] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.23, 127.0.0.1:57635]
[2022-12-10 21:43:46,408] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:43:46,410] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:57635]
[2022-12-10 21:43:53,774] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.08, 127.0.0.1:57644]
[2022-12-10 21:43:53,926] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:43:53,929] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:57644]
[2022-12-10 21:47:17,724] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:47:18,145] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:47:18,145] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:47:18,145] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:47:22,703] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.22, 127.0.0.1:57749]
[2022-12-10 21:47:22,900] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:47:22,902] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:57749]
[2022-12-10 21:47:25,849] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.05, 127.0.0.1:57749]
[2022-12-10 21:47:25,992] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:47:25,993] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:57749]
[2022-12-10 21:47:44,101] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /modules/1 200 [0.09, 127.0.0.1:57762]
[2022-12-10 21:47:59,685] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/1
[2022-12-10 21:47:59,685] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/1 404 [0.14, 127.0.0.1:57766]
[2022-12-10 21:47:59,899] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/1
[2022-12-10 21:47:59,901] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/1 404 [0.07, 127.0.0.1:57766]
[2022-12-10 21:48:00,087] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:48:00,089] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:57766]
[2022-12-10 21:48:05,833] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.06, 127.0.0.1:57774]
[2022-12-10 21:48:05,959] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:48:05,961] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:57774]
[2022-12-10 21:48:15,252] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/3 200 [0.25, 127.0.0.1:57779]
[2022-12-10 21:48:29,122] [log.py:241] [log:log_response] [WARNING]- Not Found: /project/3
[2022-12-10 21:48:29,123] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /project/3 404 [0.03, 127.0.0.1:57787]
[2022-12-10 21:48:29,193] [log.py:241] [log:log_response] [WARNING]- Not Found: /project/jquery.min.js
[2022-12-10 21:48:29,194] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /project/jquery.min.js 404 [0.02, 127.0.0.1:57787]
[2022-12-10 21:48:32,625] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.05, 127.0.0.1:57789]
[2022-12-10 21:48:32,756] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:48:32,758] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:57789]
[2022-12-10 21:48:39,403] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/3 200 [0.07, 127.0.0.1:57796]
[2022-12-10 21:48:53,998] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/3 200 [0.11, 127.0.0.1:57803]
[2022-12-10 21:48:54,175] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:48:54,177] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:57803]
[2022-12-10 21:49:09,418] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/3
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 471, in put
    pro.leader = serialize.validated_data['leader']
KeyError: 'leader'
[2022-12-10 21:49:09,418] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /modules/3 500 [0.25, 127.0.0.1:57817]
[2022-12-10 21:49:22,389] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/3 200 [0.06, 127.0.0.1:57826]
[2022-12-10 21:49:22,552] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:49:22,554] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:57826]
[2022-12-10 21:49:55,749] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/4 200 [0.29, 127.0.0.1:57851]
[2022-12-10 21:49:58,225] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:49:58,227] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:57855]
[2022-12-10 21:50:27,448] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:57870]
[2022-12-10 21:50:27,673] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 21:50:27,675] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:57870]
[2022-12-10 21:50:48,118] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/3
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 471, in put
    pro.leader = serialize.validated_data['leader']
KeyError: 'leader'
[2022-12-10 21:50:48,118] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /modules/3 500 [0.15, 127.0.0.1:57882]
[2022-12-10 21:51:34,570] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.05, 127.0.0.1:57909]
[2022-12-10 21:51:36,119] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.10, 127.0.0.1:57909]
[2022-12-10 21:51:38,937] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.07, 127.0.0.1:57916]
[2022-12-10 21:51:39,084] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:51:39,086] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:57916]
[2022-12-10 21:51:55,190] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/1
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 471, in put
    pro.leader = serialize.validated_data['leader']
KeyError: 'leader'
[2022-12-10 21:51:55,205] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP PUT /modules/1 500 [0.15, 127.0.0.1:57930]
[2022-12-10 21:53:35,174] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:53:36,219] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:53:36,219] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:53:36,235] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:53:39,419] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.45, 127.0.0.1:57997]
[2022-12-10 21:53:39,671] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:53:39,676] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.11, 127.0.0.1:57997]
[2022-12-10 21:55:28,421] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:55:28,905] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:55:28,905] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:55:28,905] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:55:29,667] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.48, 127.0.0.1:58076]
[2022-12-10 21:55:31,958] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:55:31,960] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:58076]
[2022-12-10 21:55:39,071] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-10 21:55:42,353] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-10 21:55:43,045] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-10 21:55:43,046] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-10 21:55:43,047] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-10 21:55:44,516] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.19, 127.0.0.1:58095]
[2022-12-10 21:55:44,892] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:55:44,893] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:58095]
[2022-12-10 21:55:51,878] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /modules/1 200 [0.11, 127.0.0.1:58101]
[2022-12-10 21:56:10,455] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/1 200 [0.08, 127.0.0.1:58112]
[2022-12-10 21:56:10,713] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:56:10,714] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.12, 127.0.0.1:58112]
[2022-12-10 21:56:25,673] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /modules/1 200 [0.08, 127.0.0.1:58122]
[2022-12-10 21:56:42,910] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/1 200 [0.19, 127.0.0.1:58131]
[2022-12-10 21:56:55,622] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:58138]
[2022-12-10 21:56:55,737] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:56:55,738] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:58138]
[2022-12-10 21:56:58,912] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/2 200 [0.07, 127.0.0.1:58141]
[2022-12-10 21:56:59,096] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 21:56:59,097] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:58141]
[2022-12-10 22:13:59,452] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [26.04, 127.0.0.1:58607]
[2022-12-10 22:14:18,437] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.57, 127.0.0.1:58659]
[2022-12-10 22:15:33,783] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:58751]
[2022-12-10 22:15:40,735] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:58763]
[2022-12-10 22:16:05,256] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.50, 127.0.0.1:58796]
[2022-12-10 22:16:35,640] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:58831]
[2022-12-10 22:16:47,437] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:58850]
[2022-12-10 22:17:28,499] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:58904]
[2022-12-10 22:18:10,210] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:58967]
[2022-12-10 22:18:54,044] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:59023]
[2022-12-10 22:20:04,836] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:59072]
[2022-12-10 22:21:17,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:59110]
[2022-12-10 22:23:40,062] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:59233]
[2022-12-10 22:23:51,350] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-10 22:23:51,371] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [6.68, 127.0.0.1:59243]
[2022-12-10 22:23:51,386] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-10 22:23:51,388] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.73, 127.0.0.1:59259]
[2022-12-10 22:30:14,674] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.33, 127.0.0.1:59510]
[2022-12-10 22:32:47,524] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:59576]
[2022-12-10 22:32:55,859] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:59590]
[2022-12-10 22:33:09,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.36, 127.0.0.1:59600]
[2022-12-11 11:41:03,139] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
