[2022-12-11 11:42:45,349] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:42:56,210] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:42:56,211] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:42:56,212] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:43:43,969] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [4.15, 127.0.0.1:63776]
[2022-12-11 11:43:44,635] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap.min.css 304 [0.11, 127.0.0.1:63776]
[2022-12-11 11:43:44,645] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/bootstrap-tweaks.css 304 [0.11, 127.0.0.1:63782]
[2022-12-11 11:43:44,664] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/prettify.css 304 [0.12, 127.0.0.1:63783]
[2022-12-11 11:43:44,836] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/ajax-form.js 304 [0.29, 127.0.0.1:63786]
[2022-12-11 11:43:44,845] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/css/default.css 304 [0.30, 127.0.0.1:63784]
[2022-12-11 11:43:44,870] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/jquery-3.5.1.min.js 304 [0.33, 127.0.0.1:63785]
[2022-12-11 11:43:44,876] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/csrf.js 304 [0.24, 127.0.0.1:63776]
[2022-12-11 11:43:44,883] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/bootstrap.min.js 304 [0.18, 127.0.0.1:63782]
[2022-12-11 11:43:44,888] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/prettify-min.js 304 [0.18, 127.0.0.1:63783]
[2022-12-11 11:43:44,892] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/js/default.js 304 [0.05, 127.0.0.1:63786]
[2022-12-11 11:43:44,954] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/img/grid.png 304 [0.01, 127.0.0.1:63786]
[2022-12-11 11:43:45,221] [runserver.py:151] [runserver:log_action] [INFO]- HTTP GET /static/rest_framework/fonts/glyphicons-halflings-regular.woff2 304 [0.06, 127.0.0.1:63786]
[2022-12-11 11:43:45,737] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:43:45,739] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.23, 127.0.0.1:63786]
[2022-12-11 11:44:24,598] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 11:44:49,784] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:44:50,870] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:44:50,871] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:44:50,872] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:45:03,313] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.35, 127.0.0.1:63841]
[2022-12-11 11:45:03,594] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:45:03,595] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:63841]
[2022-12-11 11:46:46,005] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:46:49,183] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:46:49,185] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:46:49,189] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:46:54,790] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [1.03, 127.0.0.1:63916]
[2022-12-11 11:46:55,278] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:46:55,283] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.28, 127.0.0.1:63916]
[2022-12-11 11:47:39,285] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.30, 127.0.0.1:63947]
[2022-12-11 11:47:39,537] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:47:39,542] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.10, 127.0.0.1:63947]
[2022-12-11 11:48:04,577] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:48:05,716] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:48:05,718] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:48:05,722] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:48:09,626] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.62, 127.0.0.1:63984]
[2022-12-11 11:48:09,977] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:48:09,982] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.13, 127.0.0.1:63984]
[2022-12-11 11:49:22,892] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:49:24,031] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:49:24,031] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:49:24,046] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:49:44,767] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [8.87, 127.0.0.1:64052]
[2022-12-11 11:49:45,075] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:49:45,079] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.12, 127.0.0.1:64052]
[2022-12-11 11:50:16,248] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:50:17,356] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:50:17,356] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:50:17,356] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:58:27,692] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:58:30,861] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:58:30,892] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:58:30,892] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 11:58:38,170] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 390, in get
    if mod['product']!=None:
KeyError: 'product'
[2022-12-11 11:58:38,182] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /modules/ 500 [0.75, 127.0.0.1:64328]
[2022-12-11 11:58:39,997] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 11:58:40,014] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.08, 127.0.0.1:64333]
[2022-12-11 11:59:21,824] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 11:59:23,649] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 11:59:23,649] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 11:59:23,664] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 12:00:51,208] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 12:00:51,948] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 12:00:51,948] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 12:00:51,950] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 12:00:55,975] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 391, in get
    pro=Project.objects.get(id=mod['product'])
KeyError: 'product'
[2022-12-11 12:00:55,986] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /modules/ 500 [0.42, 127.0.0.1:64436]
[2022-12-11 12:00:56,318] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 12:00:56,320] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.14, 127.0.0.1:64436]
[2022-12-11 12:01:09,190] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 12:01:12,459] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 12:01:13,065] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 12:01:13,067] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 12:01:13,069] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 12:01:28,890] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [8.83, 127.0.0.1:64461]
[2022-12-11 12:01:36,498] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 12:01:36,500] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:64474]
[2022-12-11 12:03:02,565] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 12:03:05,597] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 12:03:06,018] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 12:03:06,018] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 12:03:06,018] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 12:06:54,734] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [3.29, 127.0.0.1:64613]
[2022-12-11 12:07:31,572] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.32, 127.0.0.1:64632]
[2022-12-11 12:07:39,681] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.55, 127.0.0.1:64638]
[2022-12-11 12:07:55,107] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.12, 127.0.0.1:64648]
[2022-12-11 12:30:42,242] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [30.11, 127.0.0.1:49674]
[2022-12-11 12:30:42,422] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [18.37, 127.0.0.1:49720]
[2022-12-11 12:30:46,929] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 732, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "D:\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 385, in get
    page = self.paginate_queryset(queryset)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 75, in page
    number = self.validate_number(number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 53, in validate_number
    if number > self.num_pages:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 102, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 96, in count
    return c()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "D:\pythonList\web_python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')
[2022-12-11 12:30:46,949] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /projects/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 732, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "D:\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 269, in get
    page = self.paginate_queryset(queryset)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 75, in page
    number = self.validate_number(number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 53, in validate_number
    if number > self.num_pages:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 102, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 96, in count
    return c()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "D:\pythonList\web_python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')
[2022-12-11 12:30:47,064] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /projects/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 732, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "D:\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] 您的主机中的软件中止了一个已建立的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 269, in get
    page = self.paginate_queryset(queryset)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 75, in page
    number = self.validate_number(number)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 53, in validate_number
    if number > self.num_pages:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 102, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\paginator.py", line 96, in count
    return c()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 621, in count
    return self.query.get_count(using=self.db)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 559, in get_count
    return obj.get_aggregation(using, ["__count"])["__count"]
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 544, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\compiler.py", line 1396, in execute_sql
    cursor = self.connection.cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 281, in ensure_connection
    with self.wrap_database_errors:
  File "D:\pythonList\web_python310\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\backends\mysql\base.py", line 247, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 633, in connect
    self._request_authentication()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 907, in _request_authentication
    auth_packet = self._read_packet()
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 692, in _read_packet
    packet_header = self._read_bytes(4)
  File "D:\pythonList\web_python310\lib\site-packages\pymysql\connections.py", line 738, in _read_bytes
    raise err.OperationalError(
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query ([WinError 10053] 您的主机中的软件中止了一个已建立的连接。)')
[2022-12-11 12:30:48,048] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /modules/ 500 [140.13, 127.0.0.1:49589]
[2022-12-11 12:30:48,557] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /projects/ 500 [136.88, 127.0.0.1:49604]
[2022-12-11 12:30:48,560] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /projects/ 500 [128.16, 127.0.0.1:49617]
[2022-12-11 12:34:10,858] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:49856]
[2022-12-11 12:37:22,104] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:49959]
[2022-12-11 12:38:37,804] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:50024]
[2022-12-11 12:38:54,642] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:50046]
[2022-12-11 12:40:47,508] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:50109]
[2022-12-11 12:42:16,595] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50176]
[2022-12-11 12:42:17,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50185]
[2022-12-11 12:42:29,993] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50197]
[2022-12-11 12:42:41,166] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:50214]
[2022-12-11 12:43:39,349] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:50243]
[2022-12-11 12:45:21,835] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:50286]
[2022-12-11 12:46:01,415] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50309]
[2022-12-11 12:46:32,108] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:50328]
[2022-12-11 12:48:07,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:50468]
[2022-12-11 12:48:08,185] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50472]
[2022-12-11 12:48:08,331] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:50475]
[2022-12-11 12:48:40,243] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50497]
[2022-12-11 12:48:59,736] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:50508]
[2022-12-11 12:49:13,687] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.29, 127.0.0.1:50522]
[2022-12-11 12:50:26,990] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50603]
[2022-12-11 12:50:35,901] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50612]
[2022-12-11 12:50:45,649] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:50625]
[2022-12-11 12:50:59,574] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:50635]
[2022-12-11 12:51:21,473] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50651]
[2022-12-11 12:51:51,370] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50674]
[2022-12-11 12:52:01,846] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:50685]
[2022-12-11 12:52:10,502] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:50694]
[2022-12-11 12:53:31,790] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:50774]
[2022-12-11 12:53:40,524] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:50792]
[2022-12-11 12:53:47,610] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:50815]
[2022-12-11 12:54:16,611] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:50856]
[2022-12-11 12:54:38,271] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50892]
[2022-12-11 12:54:48,046] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:50911]
[2022-12-11 12:56:23,953] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:50979]
[2022-12-11 12:56:57,096] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:51013]
[2022-12-11 12:57:12,820] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [1.04, 127.0.0.1:51024]
[2022-12-11 12:57:13,398] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:51028]
[2022-12-11 12:57:15,015] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.13, 127.0.0.1:51033]
[2022-12-11 12:57:18,839] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:51043]
[2022-12-11 12:58:21,594] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.02, 127.0.0.1:51084]
[2022-12-11 12:58:32,262] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:51095]
[2022-12-11 12:58:39,454] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:51104]
[2022-12-11 12:58:52,900] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:51118]
[2022-12-11 13:00:01,335] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:51158]
[2022-12-11 13:00:20,621] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.02, 127.0.0.1:51169]
[2022-12-11 13:00:33,947] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51181]
[2022-12-11 13:00:55,672] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:51195]
[2022-12-11 13:03:27,992] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51389]
[2022-12-11 13:04:31,560] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:51425]
[2022-12-11 13:05:48,137] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51477]
[2022-12-11 13:06:10,935] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51493]
[2022-12-11 13:06:25,387] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:51502]
[2022-12-11 13:08:50,552] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51566]
[2022-12-11 13:09:03,630] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51578]
[2022-12-11 13:09:05,050] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.17, 127.0.0.1:51581]
[2022-12-11 13:09:12,254] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51593]
[2022-12-11 13:09:28,322] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51605]
[2022-12-11 14:00:55,480] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.71, 127.0.0.1:52861]
[2022-12-11 14:03:59,390] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.41, 127.0.0.1:53009]
[2022-12-11 14:03:59,861] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.30, 127.0.0.1:53014]
[2022-12-11 14:04:08,106] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:53025]
[2022-12-11 14:04:40,638] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:53044]
[2022-12-11 14:05:14,808] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:53065]
[2022-12-11 14:05:44,236] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:53094]
[2022-12-11 14:06:08,830] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=2 200 [1.24, 127.0.0.1:53121]
[2022-12-11 14:06:20,490] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.31, 127.0.0.1:53137]
[2022-12-11 14:06:47,182] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=%E8%B4%9F%E8%B4%A3%E4%BA%BA 200 [0.22, 127.0.0.1:53153]
[2022-12-11 14:06:52,170] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.19, 127.0.0.1:53160]
[2022-12-11 14:07:52,825] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [2.62, 127.0.0.1:53188]
[2022-12-11 14:07:53,720] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:53193]
[2022-12-11 14:19:40,670] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:53557]
[2022-12-11 14:20:39,716] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.92, 127.0.0.1:53595]
[2022-12-11 14:20:48,298] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.51, 127.0.0.1:53605]
[2022-12-11 14:24:45,465] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.37, 127.0.0.1:53711]
[2022-12-11 14:24:48,770] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:53719]
[2022-12-11 14:25:55,264] [server.py:271] [server:application_checker] [WARNING]- Application instance <Task pending name='Task-85' coro=<StaticFilesWrapper.__call__() running at D:\pythonList\web_python310\lib\site-packages\channels\staticfiles.py:44> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at D:\Python310\lib\asyncio\futures.py:384, Task.task_wakeup()]>> for connection <WebRequest at 0x54dffe8 method=GET uri=/modules/ clientproto=HTTP/1.1> took too long to shut down and was killed.
[2022-12-11 14:26:02,062] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [17.78, 127.0.0.1:53747]
[2022-12-11 14:26:07,551] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 14:26:07,578] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [1.15, 127.0.0.1:53761]
[2022-12-11 14:27:16,535] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.02, 127.0.0.1:53815]
[2022-12-11 14:28:48,781] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [1.31, 127.0.0.1:53932]
[2022-12-11 14:28:57,045] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:53950]
[2022-12-11 14:29:04,016] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:53959]
[2022-12-11 14:29:04,317] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 14:29:04,318] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:53959]
[2022-12-11 14:29:23,579] [runserver.py:147] [runserver:log_action] [INFO]- HTTP OPTIONS /projects/ 200 [0.03, 127.0.0.1:53970]
[2022-12-11 14:29:32,763] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:53976]
[2022-12-11 14:29:32,908] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 14:29:32,910] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:53976]
[2022-12-11 14:29:34,961] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.08, 127.0.0.1:53976]
[2022-12-11 14:29:35,105] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 14:29:35,108] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:53976]
[2022-12-11 14:41:26,237] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 14:41:26,239] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.05, 127.0.0.1:54599]
[2022-12-11 14:44:28,450] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.21, 127.0.0.1:54681]
[2022-12-11 14:49:36,361] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.56, 127.0.0.1:54995]
[2022-12-11 14:49:46,535] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.28, 127.0.0.1:55009]
[2022-12-11 14:57:47,241] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.54, 127.0.0.1:55290]
[2022-12-11 14:57:47,641] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.34, 127.0.0.1:55295]
[2022-12-11 14:57:47,892] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:55297]
[2022-12-11 14:57:48,449] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:55301]
[2022-12-11 15:00:02,463] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:55370]
[2022-12-11 15:02:36,074] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:55433]
[2022-12-11 15:11:45,069] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 15:11:45,267] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [3.94, 127.0.0.1:56247]
[2022-12-11 15:11:59,300] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/1
[2022-12-11 15:11:59,301] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/1 404 [9.05, 127.0.0.1:56252]
[2022-12-11 15:11:59,330] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/15 200 [5.57, 127.0.0.1:56253]
[2022-12-11 15:12:00,598] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 15:12:00,600] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.41, 127.0.0.1:56253]
[2022-12-11 15:15:44,159] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/2 200 [0.70, 127.0.0.1:56541]
[2022-12-11 15:15:44,605] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 15:15:44,607] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.06, 127.0.0.1:56541]
[2022-12-11 15:43:52,178] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [46.78, 127.0.0.1:58661]
[2022-12-11 15:44:14,856] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.74, 127.0.0.1:58757]
[2022-12-11 15:44:27,457] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.22, 127.0.0.1:58767]
[2022-12-11 15:45:25,208] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.51, 127.0.0.1:58806]
[2022-12-11 15:45:33,284] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/${this.form.id}
[2022-12-11 15:45:33,400] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/$%7Bthis.form.id%7D 404 [2.62, 127.0.0.1:58813]
[2022-12-11 15:45:33,523] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.47, 127.0.0.1:58815]
[2022-12-11 15:45:36,772] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/${this.form.id}
[2022-12-11 15:45:36,773] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/$%7Bthis.form.id%7D 404 [0.08, 127.0.0.1:58823]
[2022-12-11 15:47:15,967] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:58872]
[2022-12-11 15:47:16,567] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:58877]
[2022-12-11 15:48:47,293] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:58979]
[2022-12-11 15:49:37,128] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:59048]
[2022-12-11 15:49:56,552] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:59075]
[2022-12-11 15:50:03,087] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/${this.form.id}
[2022-12-11 15:50:03,087] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/$%7Bthis.form.id%7D 404 [0.15, 127.0.0.1:59088]
[2022-12-11 15:52:19,989] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:59265]
[2022-12-11 15:59:44,304] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [3.49, 127.0.0.1:60324]
[2022-12-11 16:00:26,716] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.85, 127.0.0.1:60393]
[2022-12-11 16:01:16,711] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.62, 127.0.0.1:60468]
[2022-12-11 16:02:25,596] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.53, 127.0.0.1:60558]
[2022-12-11 16:02:31,142] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:02:31,148] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/undefined 404 [2.74, 127.0.0.1:60567]
[2022-12-11 16:04:04,292] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:60687]
[2022-12-11 16:04:09,779] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [1.56, 127.0.0.1:60696]
[2022-12-11 16:04:29,628] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.25, 127.0.0.1:60726]
[2022-12-11 16:04:34,463] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.18, 127.0.0.1:60739]
[2022-12-11 16:05:18,778] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.18, 127.0.0.1:60806]
[2022-12-11 16:05:21,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:60815]
[2022-12-11 16:05:26,011] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.25, 127.0.0.1:60827]
[2022-12-11 16:05:52,360] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:60858]
[2022-12-11 16:05:52,956] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:05:52,958] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/undefined 404 [0.05, 127.0.0.1:60862]
[2022-12-11 16:06:17,982] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:60900]
[2022-12-11 16:06:22,637] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:06:22,638] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/undefined 404 [0.03, 127.0.0.1:60912]
[2022-12-11 16:07:43,067] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:07:43,070] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/undefined 404 [0.04, 127.0.0.1:61008]
[2022-12-11 16:07:53,007] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:61025]
[2022-12-11 16:07:54,038] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:07:54,070] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/undefined 404 [0.09, 127.0.0.1:61029]
[2022-12-11 16:08:54,767] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:61134]
[2022-12-11 16:09:01,155] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:61148]
[2022-12-11 16:09:04,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.07, 127.0.0.1:61159]
[2022-12-11 16:09:07,643] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:61163]
[2022-12-11 16:11:08,785] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:61315]
[2022-12-11 16:11:12,850] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.15, 127.0.0.1:61327]
[2022-12-11 16:11:15,353] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:61335]
[2022-12-11 16:11:18,029] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/4 200 [0.05, 127.0.0.1:61341]
[2022-12-11 16:11:20,721] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:61349]
[2022-12-11 16:11:33,719] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/12 200 [0.14, 127.0.0.1:61372]
[2022-12-11 16:11:36,828] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:61381]
[2022-12-11 16:11:47,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.09, 127.0.0.1:61400]
[2022-12-11 16:11:56,713] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [2.33, 127.0.0.1:61412]
[2022-12-11 16:11:57,399] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:61421]
[2022-12-11 16:13:19,315] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:61530]
[2022-12-11 16:13:31,805] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/5 200 [4.63, 127.0.0.1:61546]
[2022-12-11 16:13:45,787] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.28, 127.0.0.1:61575]
[2022-12-11 16:13:46,911] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:61579]
[2022-12-11 16:13:59,690] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:61592]
[2022-12-11 16:14:02,934] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:61598]
[2022-12-11 16:14:10,710] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.06, 127.0.0.1:61605]
[2022-12-11 16:18:56,337] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.10, 127.0.0.1:61725]
[2022-12-11 16:19:10,448] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:19:10,449] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.20, 127.0.0.1:61741]
[2022-12-11 16:19:10,496] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 16:19:10,498] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.15, 127.0.0.1:61742]
[2022-12-11 16:19:29,276] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [7.97, 127.0.0.1:61752]
[2022-12-11 16:19:29,860] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:19:29,861] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:61752]
[2022-12-11 16:19:33,380] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.43, 127.0.0.1:61765]
[2022-12-11 16:19:33,659] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:19:33,661] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.08, 127.0.0.1:61765]
[2022-12-11 16:19:48,935] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/1
[2022-12-11 16:19:48,935] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/1 404 [1.39, 127.0.0.1:61773]
[2022-12-11 16:19:49,813] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/17 200 [0.39, 127.0.0.1:61773]
[2022-12-11 16:19:49,980] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:19:49,982] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:61773]
[2022-12-11 16:20:03,879] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/17 200 [0.22, 127.0.0.1:61783]
[2022-12-11 16:20:09,924] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/17 200 [0.19, 127.0.0.1:61790]
[2022-12-11 16:20:10,115] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:20:10,117] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.05, 127.0.0.1:61790]
[2022-12-11 16:20:31,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/3 200 [0.10, 127.0.0.1:61803]
[2022-12-11 16:20:34,654] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:61811]
[2022-12-11 16:20:55,824] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.06, 127.0.0.1:61827]
[2022-12-11 16:20:57,771] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:61834]
[2022-12-11 16:20:59,964] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /projects?search=dd 301 [0.01, 127.0.0.1:61837]
[2022-12-11 16:22:38,929] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.19, 127.0.0.1:61950]
[2022-12-11 16:22:39,146] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:22:39,149] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:61950]
[2022-12-11 16:22:46,162] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=dd 200 [0.45, 127.0.0.1:61959]
[2022-12-11 16:22:46,369] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:22:46,371] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:61959]
[2022-12-11 16:28:00,131] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.50, 127.0.0.1:62335]
[2022-12-11 16:28:03,435] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=dd 200 [0.11, 127.0.0.1:62345]
[2022-12-11 16:28:13,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/18 200 [0.10, 127.0.0.1:62360]
[2022-12-11 16:28:31,957] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.16, 127.0.0.1:62372]
[2022-12-11 16:28:35,001] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:62381]
[2022-12-11 16:28:39,612] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=whd 200 [0.11, 127.0.0.1:62388]
[2022-12-11 16:28:49,591] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:62394]
[2022-12-11 16:28:49,834] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:28:49,836] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:62394]
[2022-12-11 16:28:54,852] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.11, 127.0.0.1:62402]
[2022-12-11 16:28:55,052] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:28:55,054] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:62402]
[2022-12-11 16:29:40,747] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/19 200 [0.11, 127.0.0.1:62433]
[2022-12-11 16:29:50,564] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:62444]
[2022-12-11 16:29:51,198] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:62447]
[2022-12-11 16:29:58,341] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.13, 127.0.0.1:62451]
[2022-12-11 16:29:58,511] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:29:58,514] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:62451]
[2022-12-11 16:30:06,891] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=dd 200 [0.06, 127.0.0.1:62462]
[2022-12-11 16:30:10,589] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/18 200 [0.07, 127.0.0.1:62470]
[2022-12-11 16:30:15,407] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/18 200 [0.08, 127.0.0.1:62480]
[2022-12-11 16:30:17,370] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:62484]
[2022-12-11 16:30:22,144] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.10, 127.0.0.1:62490]
[2022-12-11 16:30:22,316] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 16:30:22,318] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.03, 127.0.0.1:62490]
[2022-12-11 16:44:50,658] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.17, 127.0.0.1:62865]
[2022-12-11 16:44:52,283] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:62869]
[2022-12-11 16:44:54,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.17, 127.0.0.1:62876]
[2022-12-11 16:45:03,250] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=%E9%A1%B9%E7%9B%AE 200 [0.12, 127.0.0.1:62883]
[2022-12-11 16:45:08,265] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.12, 127.0.0.1:62891]
[2022-12-11 16:50:29,845] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:63138]
[2022-12-11 16:50:38,259] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/8 200 [3.53, 127.0.0.1:63157]
[2022-12-11 16:50:38,277] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/9 200 [3.46, 127.0.0.1:63160]
[2022-12-11 16:50:38,404] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/10 200 [3.43, 127.0.0.1:63163]
[2022-12-11 16:50:38,408] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/6 200 [4.03, 127.0.0.1:63146]
[2022-12-11 16:50:38,557] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/7 200 [4.16, 127.0.0.1:63149]
[2022-12-11 16:50:39,368] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/13 200 [0.72, 127.0.0.1:63176]
[2022-12-11 16:50:39,395] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/4 200 [0.67, 127.0.0.1:63181]
[2022-12-11 16:50:39,397] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/12 200 [0.67, 127.0.0.1:63180]
[2022-12-11 16:50:39,400] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/3 200 [4.47, 127.0.0.1:63161]
[2022-12-11 16:50:39,403] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/11 200 [0.83, 127.0.0.1:63173]
[2022-12-11 16:50:43,172] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:63189]
[2022-12-11 16:50:48,601] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.22, 127.0.0.1:63201]
[2022-12-11 16:50:51,847] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:63206]
[2022-12-11 16:50:56,698] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/14 200 [0.19, 127.0.0.1:63220]
[2022-12-11 16:50:56,783] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/18 200 [0.16, 127.0.0.1:63230]
[2022-12-11 16:50:56,833] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/15 200 [0.28, 127.0.0.1:63224]
[2022-12-11 16:50:56,872] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/17 200 [0.25, 127.0.0.1:63231]
[2022-12-11 16:50:56,903] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/16 200 [0.34, 127.0.0.1:63225]
[2022-12-11 16:51:01,530] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.13, 127.0.0.1:63240]
[2022-12-11 16:51:01,936] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:63243]
[2022-12-11 16:51:04,519] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.16, 127.0.0.1:63248]
[2022-12-11 16:51:09,410] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:63258]
[2022-12-11 16:51:28,696] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:51:28,790] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP PUT /projects/undefined 404 [1.33, 127.0.0.1:63275]
[2022-12-11 16:51:29,185] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:63278]
[2022-12-11 16:51:31,478] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:63285]
[2022-12-11 16:51:32,520] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.18, 127.0.0.1:63288]
[2022-12-11 16:51:34,995] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:63294]
[2022-12-11 16:51:35,553] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:63300]
[2022-12-11 16:52:48,672] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/undefined
[2022-12-11 16:52:48,674] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP PUT /projects/undefined 404 [0.33, 127.0.0.1:63369]
[2022-12-11 17:08:34,771] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:64501]
[2022-12-11 17:08:40,749] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.40, 127.0.0.1:64512]
[2022-12-11 17:08:42,696] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:64523]
[2022-12-11 17:08:54,092] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.72, 127.0.0.1:64543]
[2022-12-11 17:09:00,744] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:64557]
[2022-12-11 17:09:04,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/20 200 [0.09, 127.0.0.1:64569]
[2022-12-11 17:09:13,751] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/20 200 [0.12, 127.0.0.1:64587]
[2022-12-11 17:09:16,565] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:64596]
[2022-12-11 17:09:24,536] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/20 200 [0.09, 127.0.0.1:64609]
[2022-12-11 17:15:05,323] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.59, 127.0.0.1:64780]
[2022-12-11 17:17:33,758] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.15, 127.0.0.1:64868]
[2022-12-11 17:17:39,665] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:64876]
[2022-12-11 17:18:02,618] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/21 200 [0.13, 127.0.0.1:64894]
[2022-12-11 17:18:11,217] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/21 200 [0.14, 127.0.0.1:64904]
[2022-12-11 17:18:13,445] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.16, 127.0.0.1:64907]
[2022-12-11 17:18:48,676] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 17:18:48,678] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.13, 127.0.0.1:64922]
[2022-12-11 17:19:00,433] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [3.08, 127.0.0.1:64924]
[2022-12-11 17:19:00,878] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 17:19:00,879] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.08, 127.0.0.1:64924]
[2022-12-11 17:19:20,678] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/21 200 [0.11, 127.0.0.1:64945]
[2022-12-11 17:19:24,166] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/21 200 [0.16, 127.0.0.1:64949]
[2022-12-11 17:19:26,270] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:64954]
[2022-12-11 17:19:30,653] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:64959]
[2022-12-11 17:19:30,917] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 17:19:30,919] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.04, 127.0.0.1:64959]
[2022-12-11 17:23:02,088] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 17:26:44,501] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 17:26:52,709] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 17:26:52,771] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 17:26:52,771] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 17:27:04,157] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.26, 127.0.0.1:65181]
[2022-12-11 17:27:08,986] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/21 200 [0.17, 127.0.0.1:65191]
[2022-12-11 17:27:34,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/21 200 [0.37, 127.0.0.1:65207]
[2022-12-11 17:27:36,562] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:65214]
[2022-12-11 17:27:45,446] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:65225]
[2022-12-11 17:27:46,890] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:65228]
[2022-12-11 17:27:50,819] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=3 200 [0.30, 127.0.0.1:65234]
[2022-12-11 17:27:55,326] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.19, 127.0.0.1:65240]
[2022-12-11 17:27:56,102] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:65245]
[2022-12-11 17:27:58,807] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/21 200 [0.12, 127.0.0.1:65249]
[2022-12-11 17:28:03,355] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/21 200 [0.09, 127.0.0.1:65258]
[2022-12-11 17:28:04,983] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.11, 127.0.0.1:65261]
[2022-12-11 17:28:09,573] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/22 200 [0.05, 127.0.0.1:65268]
[2022-12-11 17:28:16,188] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/22 200 [0.14, 127.0.0.1:65276]
[2022-12-11 17:28:17,556] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:65281]
[2022-12-11 17:28:20,693] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=1 200 [0.09, 127.0.0.1:65286]
[2022-12-11 17:28:24,448] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.08, 127.0.0.1:65293]
[2022-12-11 17:28:26,345] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=2 200 [0.08, 127.0.0.1:65298]
[2022-12-11 17:28:30,095] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.09, 127.0.0.1:65301]
[2022-12-11 17:28:33,705] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=3 200 [0.07, 127.0.0.1:65308]
[2022-12-11 17:28:37,181] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.09, 127.0.0.1:65316]
[2022-12-11 17:29:39,206] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 17:30:03,034] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 17:30:03,580] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 17:30:03,581] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 17:30:03,583] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 17:30:08,553] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.12, 127.0.0.1:65364]
[2022-12-11 17:30:12,816] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.12, 127.0.0.1:65370]
[2022-12-11 17:30:14,501] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.11, 127.0.0.1:65373]
[2022-12-11 17:30:16,652] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.10, 127.0.0.1:65379]
[2022-12-11 17:30:18,716] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.06, 127.0.0.1:65383]
[2022-12-11 17:30:21,516] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.13, 127.0.0.1:65390]
[2022-12-11 17:30:23,439] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.17, 127.0.0.1:65394]
[2022-12-11 17:30:25,708] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.07, 127.0.0.1:65400]
[2022-12-11 17:30:27,661] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.07, 127.0.0.1:65405]
[2022-12-11 17:30:31,991] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.09, 127.0.0.1:65410]
[2022-12-11 17:30:33,586] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.05, 127.0.0.1:65413]
[2022-12-11 17:30:35,902] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.16, 127.0.0.1:65418]
[2022-12-11 17:30:39,091] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.08, 127.0.0.1:65422]
[2022-12-11 17:30:43,146] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.04, 127.0.0.1:65431]
[2022-12-11 17:30:45,779] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.08, 127.0.0.1:65438]
[2022-12-11 17:30:46,901] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:65441]
[2022-12-11 17:50:38,975] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=22 200 [0.15, 127.0.0.1:49613]
[2022-12-11 17:50:42,820] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.14, 127.0.0.1:49619]
[2022-12-11 17:51:10,097] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.15, 127.0.0.1:49638]
[2022-12-11 18:08:45,297] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 18:08:45,443] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [13.80, 127.0.0.1:50683]
[2022-12-11 18:12:48,702] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [24.74, 127.0.0.1:50967]
[2022-12-11 18:12:49,272] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 18:12:49,274] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.10, 127.0.0.1:50967]
[2022-12-11 18:13:04,511] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /projects?size=20 301 [0.01, 127.0.0.1:51023]
[2022-12-11 18:13:05,169] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=20 200 [0.62, 127.0.0.1:51023]
[2022-12-11 18:13:05,433] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 18:13:05,435] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.05, 127.0.0.1:51023]
[2022-12-11 18:18:57,510] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10 200 [0.54, 127.0.0.1:51477]
[2022-12-11 18:18:58,118] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 18:18:58,119] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.08, 127.0.0.1:51477]
[2022-12-11 18:19:17,118] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.30, 127.0.0.1:51511]
[2022-12-11 18:19:18,580] [log.py:241] [log:log_response] [WARNING]- Not Found: /projects/jquery.min.js
[2022-12-11 18:19:18,582] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /projects/jquery.min.js 404 [0.06, 127.0.0.1:51511]
[2022-12-11 18:20:02,564] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [1.70, 127.0.0.1:51569]
[2022-12-11 18:20:11,693] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=50 200 [1.41, 127.0.0.1:51589]
[2022-12-11 18:20:26,083] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [1.30, 127.0.0.1:51609]
[2022-12-11 18:20:27,869] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.61, 127.0.0.1:51616]
[2022-12-11 18:20:33,289] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.62, 127.0.0.1:51624]
[2022-12-11 18:20:38,155] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.29, 127.0.0.1:51634]
[2022-12-11 18:21:01,594] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.23, 127.0.0.1:51650]
[2022-12-11 18:21:04,276] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.13, 127.0.0.1:51655]
[2022-12-11 18:21:05,990] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.17, 127.0.0.1:51660]
[2022-12-11 18:21:09,161] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500 200 [0.14, 127.0.0.1:51667]
[2022-12-11 18:21:12,749] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10 200 [0.13, 127.0.0.1:51674]
[2022-12-11 18:21:13,518] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.10, 127.0.0.1:51677]
[2022-12-11 18:21:16,926] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500 200 [0.21, 127.0.0.1:51686]
[2022-12-11 18:21:17,041] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.30, 127.0.0.1:51689]
[2022-12-11 18:21:24,190] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10 200 [0.17, 127.0.0.1:51700]
[2022-12-11 18:21:29,337] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.12, 127.0.0.1:51708]
[2022-12-11 18:21:34,899] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500 200 [0.09, 127.0.0.1:51717]
[2022-12-11 18:21:34,936] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.11, 127.0.0.1:51718]
[2022-12-11 18:22:47,234] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:51755]
[2022-12-11 18:22:49,458] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.12, 127.0.0.1:51758]
[2022-12-11 18:22:51,204] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.11, 127.0.0.1:51765]
[2022-12-11 18:22:55,224] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.14, 127.0.0.1:51770]
[2022-12-11 18:22:58,412] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.14, 127.0.0.1:51777]
[2022-12-11 18:22:58,443] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.17, 127.0.0.1:51778]
[2022-12-11 18:23:25,482] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.10, 127.0.0.1:51796]
[2022-12-11 18:23:55,362] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=2 200 [0.26, 127.0.0.1:51828]
[2022-12-11 18:24:04,871] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.13, 127.0.0.1:51846]
[2022-12-11 18:24:04,887] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?page=1 200 [0.13, 127.0.0.1:51849]
[2022-12-11 18:26:43,506] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.17, 127.0.0.1:52045]
[2022-12-11 18:26:56,096] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.11, 127.0.0.1:52066]
[2022-12-11 18:26:57,863] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.09, 127.0.0.1:52073]
[2022-12-11 18:27:02,785] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.13, 127.0.0.1:52080]
[2022-12-11 18:27:06,347] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.24, 127.0.0.1:52084]
[2022-12-11 18:27:08,092] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.31, 127.0.0.1:52089]
[2022-12-11 18:27:11,171] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.10, 127.0.0.1:52093]
[2022-12-11 18:27:11,454] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.07, 127.0.0.1:52097]
[2022-12-11 18:28:04,035] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.27, 127.0.0.1:52151]
[2022-12-11 18:28:06,044] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:52154]
[2022-12-11 18:28:07,308] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:52159]
[2022-12-11 18:28:09,557] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.07, 127.0.0.1:52163]
[2022-12-11 18:28:11,235] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.14, 127.0.0.1:52169]
[2022-12-11 18:28:14,410] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.05, 127.0.0.1:52175]
[2022-12-11 18:28:17,940] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.18, 127.0.0.1:52184]
[2022-12-11 18:28:19,317] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.09, 127.0.0.1:52189]
[2022-12-11 18:28:21,824] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.15, 127.0.0.1:52195]
[2022-12-11 18:28:22,064] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.14, 127.0.0.1:52199]
[2022-12-11 18:28:25,285] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.13, 127.0.0.1:52203]
[2022-12-11 18:28:26,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.10, 127.0.0.1:52208]
[2022-12-11 18:28:30,450] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.14, 127.0.0.1:52213]
[2022-12-11 18:28:30,835] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.07, 127.0.0.1:52217]
[2022-12-11 18:28:33,920] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.10, 127.0.0.1:52223]
[2022-12-11 18:28:39,666] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.11, 127.0.0.1:52234]
[2022-12-11 18:28:41,373] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.17, 127.0.0.1:52239]
[2022-12-11 18:28:52,898] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.17, 127.0.0.1:52246]
[2022-12-11 18:28:54,320] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:52250]
[2022-12-11 18:29:10,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.10, 127.0.0.1:52263]
[2022-12-11 18:29:19,865] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:52272]
[2022-12-11 18:29:22,112] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=2 200 [0.03, 127.0.0.1:52282]
[2022-12-11 18:29:23,677] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.10, 127.0.0.1:52286]
[2022-12-11 18:29:34,482] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=500&page=1 200 [0.08, 127.0.0.1:52295]
[2022-12-11 18:29:42,899] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/22 200 [5.37, 127.0.0.1:52311]
[2022-12-11 18:29:42,935] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/24 200 [5.40, 127.0.0.1:52313]
[2022-12-11 18:29:42,947] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/26 200 [5.39, 127.0.0.1:52316]
[2022-12-11 18:29:42,949] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/23 200 [5.41, 127.0.0.1:52312]
[2022-12-11 18:29:42,953] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/21 200 [5.42, 127.0.0.1:52310]
[2022-12-11 18:29:43,469] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/25 200 [5.93, 127.0.0.1:52314]
[2022-12-11 18:29:44,861] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/29 200 [1.42, 127.0.0.1:52340]
[2022-12-11 18:29:44,902] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/32 200 [1.11, 127.0.0.1:52350]
[2022-12-11 18:29:44,955] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/30 200 [1.51, 127.0.0.1:52341]
[2022-12-11 18:29:44,957] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/31 200 [1.52, 127.0.0.1:52342]
[2022-12-11 18:29:44,961] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/27 200 [1.52, 127.0.0.1:52338]
[2022-12-11 18:29:44,962] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/28 200 [1.52, 127.0.0.1:52339]
[2022-12-11 18:29:45,867] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/35 200 [0.59, 127.0.0.1:52362]
[2022-12-11 18:29:45,907] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/34 200 [0.69, 127.0.0.1:52359]
[2022-12-11 18:29:45,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /projects/33 200 [0.74, 127.0.0.1:52356]
[2022-12-11 18:30:12,808] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.48, 127.0.0.1:52378]
[2022-12-11 18:30:22,047] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.14, 127.0.0.1:52387]
[2022-12-11 18:30:23,529] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:52393]
[2022-12-11 18:30:34,921] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/36 200 [0.14, 127.0.0.1:52400]
[2022-12-11 18:30:43,604] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/36 200 [0.09, 127.0.0.1:52410]
[2022-12-11 18:30:45,347] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52414]
[2022-12-11 18:30:48,951] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/36 200 [0.12, 127.0.0.1:52421]
[2022-12-11 18:30:59,111] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /projects/36 200 [0.25, 127.0.0.1:52432]
[2022-12-11 18:30:59,942] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52435]
[2022-12-11 18:31:12,354] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=x 200 [0.20, 127.0.0.1:52447]
[2022-12-11 18:31:16,770] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.12, 127.0.0.1:52453]
[2022-12-11 18:31:20,429] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search=m 200 [0.11, 127.0.0.1:52461]
[2022-12-11 18:31:23,193] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?search= 200 [0.09, 127.0.0.1:52464]
[2022-12-11 18:32:51,253] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.15, 127.0.0.1:52505]
[2022-12-11 18:33:19,163] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:52521]
[2022-12-11 18:33:43,274] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:52538]
[2022-12-11 18:33:53,580] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:52549]
[2022-12-11 18:33:56,402] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:52557]
[2022-12-11 18:36:48,340] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.12, 127.0.0.1:52640]
[2022-12-11 18:55:10,913] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.49, 127.0.0.1:53661]
[2022-12-11 18:55:14,160] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.24, 127.0.0.1:53668]
[2022-12-11 18:55:15,111] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.13, 127.0.0.1:53671]
[2022-12-11 19:03:08,141] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [2.52, 127.0.0.1:53929]
[2022-12-11 19:03:11,695] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [2.49, 127.0.0.1:53937]
[2022-12-11 19:03:12,568] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [2.23, 127.0.0.1:53940]
[2022-12-11 19:03:13,371] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.90, 127.0.0.1:53945]
[2022-12-11 19:03:19,172] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=50&page=1 200 [0.84, 127.0.0.1:53952]
[2022-12-11 19:03:24,819] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/?size=10&page=1 200 [0.73, 127.0.0.1:53961]
[2022-12-11 19:03:26,955] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.52, 127.0.0.1:53966]
[2022-12-11 19:03:44,209] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.41, 127.0.0.1:53978]
[2022-12-11 19:03:46,967] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.90, 127.0.0.1:53982]
[2022-12-11 19:03:48,556] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.55, 127.0.0.1:53988]
[2022-12-11 19:03:50,329] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.79, 127.0.0.1:53995]
[2022-12-11 19:03:54,210] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.69, 127.0.0.1:54001]
[2022-12-11 19:24:33,538] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 19:24:46,566] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 19:24:46,582] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 19:24:46,582] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 19:41:07,564] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 19:41:23,898] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 19:41:23,898] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 19:41:23,913] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 19:45:36,979] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [2.71, 127.0.0.1:49253]
[2022-12-11 19:45:39,705] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.39, 127.0.0.1:49263]
[2022-12-11 19:45:41,803] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:49287]
[2022-12-11 19:47:53,296] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:49614]
[2022-12-11 19:48:29,311] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:49661]
[2022-12-11 19:50:02,935] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:49784]
[2022-12-11 19:50:03,191] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:49789]
[2022-12-11 19:50:04,610] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:49798]
[2022-12-11 19:50:14,748] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.13, 127.0.0.1:49819]
[2022-12-11 19:55:50,226] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.46, 127.0.0.1:50320]
[2022-12-11 19:56:01,802] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [2.43, 127.0.0.1:50345]
[2022-12-11 19:56:54,482] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:50410]
[2022-12-11 19:56:55,142] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50413]
[2022-12-11 19:56:56,435] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.17, 127.0.0.1:50420]
[2022-12-11 19:58:00,342] [log.py:241] [log:log_response] [WARNING]- Not Found: /
[2022-12-11 19:58:00,343] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET / 404 [0.41, 127.0.0.1:50463]
[2022-12-11 19:58:00,523] [log.py:241] [log:log_response] [WARNING]- Not Found: /jquery.min.js
[2022-12-11 19:58:00,525] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /jquery.min.js 404 [0.02, 127.0.0.1:50463]
[2022-12-11 19:58:00,603] [log.py:241] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2022-12-11 19:58:00,605] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /favicon.ico 404 [0.05, 127.0.0.1:50463]
[2022-12-11 19:58:09,477] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [2.67, 127.0.0.1:50469]
[2022-12-11 19:58:10,220] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 19:58:10,222] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:50469]
[2022-12-11 20:02:41,187] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.33, 127.0.0.1:50784]
[2022-12-11 20:02:43,311] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.12, 127.0.0.1:50795]
[2022-12-11 20:02:44,301] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:50799]
[2022-12-11 20:03:05,954] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [1.95, 127.0.0.1:50828]
[2022-12-11 20:03:12,527] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:50844]
[2022-12-11 20:03:25,887] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:50861]
[2022-12-11 20:06:01,046] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:50931]
[2022-12-11 20:06:12,250] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:50942]
[2022-12-11 20:06:25,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /projects/ 200 [0.06, 127.0.0.1:50951]
[2022-12-11 20:06:26,605] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.04, 127.0.0.1:50955]
[2022-12-11 20:06:28,285] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:50961]
[2022-12-11 20:06:47,266] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.09, 127.0.0.1:50975]
[2022-12-11 20:06:48,579] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:50978]
[2022-12-11 20:07:59,705] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:51014]
[2022-12-11 20:08:47,766] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:51039]
[2022-12-11 20:09:09,471] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:51054]
[2022-12-11 20:12:18,626] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.11, 127.0.0.1:51143]
[2022-12-11 20:13:44,497] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:51187]
[2022-12-11 20:13:48,876] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/10 200 [0.09, 127.0.0.1:51194]
[2022-12-11 20:17:47,326] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51305]
[2022-12-11 20:17:47,559] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/10 200 [0.08, 127.0.0.1:51308]
[2022-12-11 20:17:56,296] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:51317]
[2022-12-11 20:18:01,737] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/11 200 [0.12, 127.0.0.1:51328]
[2022-12-11 20:18:01,919] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.30, 127.0.0.1:51329]
[2022-12-11 20:18:07,822] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:51338]
[2022-12-11 20:18:12,239] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/10 200 [0.08, 127.0.0.1:51349]
[2022-12-11 20:18:12,258] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.10, 127.0.0.1:51350]
[2022-12-11 20:18:27,262] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:51358]
[2022-12-11 20:18:33,338] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/9 200 [0.04, 127.0.0.1:51376]
[2022-12-11 20:18:33,343] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:51373]
[2022-12-11 20:18:36,505] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:51380]
[2022-12-11 20:18:44,645] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.14, 127.0.0.1:51389]
[2022-12-11 20:18:44,648] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/11 200 [0.14, 127.0.0.1:51390]
[2022-12-11 20:18:52,190] [runserver.py:147] [runserver:log_action] [INFO]- HTTP PUT /modules/11 200 [0.47, 127.0.0.1:51403]
[2022-12-11 20:18:54,137] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:51409]
[2022-12-11 20:19:55,397] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:51446]
[2022-12-11 20:20:00,567] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/7 200 [0.38, 127.0.0.1:51467]
[2022-12-11 20:20:00,583] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/6 200 [0.42, 127.0.0.1:51466]
[2022-12-11 20:20:00,599] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/5 200 [0.44, 127.0.0.1:51465]
[2022-12-11 20:20:00,638] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/4 200 [0.48, 127.0.0.1:51464]
[2022-12-11 20:20:00,640] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/2 200 [0.49, 127.0.0.1:51462]
[2022-12-11 20:20:00,644] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/3 200 [0.49, 127.0.0.1:51463]
[2022-12-11 20:20:01,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/8 200 [0.18, 127.0.0.1:51479]
[2022-12-11 20:20:01,077] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/10 200 [0.15, 127.0.0.1:51485]
[2022-12-11 20:20:01,093] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/9 200 [0.18, 127.0.0.1:51482]
[2022-12-11 20:20:01,093] [runserver.py:147] [runserver:log_action] [INFO]- HTTP DELETE /modules/11 200 [0.14, 127.0.0.1:51488]
[2022-12-11 20:20:03,460] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:51493]
[2022-12-11 20:20:04,606] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:51497]
[2022-12-11 20:20:06,213] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:51503]
[2022-12-11 20:20:17,279] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.02, 127.0.0.1:51514]
[2022-12-11 20:20:18,357] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:51517]
[2022-12-11 20:20:27,093] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.05, 127.0.0.1:51525]
[2022-12-11 20:20:36,225] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.14, 127.0.0.1:51535]
[2022-12-11 20:20:37,036] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:51539]
[2022-12-11 20:21:18,993] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:51561]
[2022-12-11 20:22:53,650] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:22:57,363] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:22:57,363] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:22:57,363] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:23:23,101] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [1.59, 127.0.0.1:51630]
[2022-12-11 20:23:27,839] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 20:23:27,840] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.26, 127.0.0.1:51634]
[2022-12-11 20:23:50,210] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /modules/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 385, in get
    queryset = self.filter_queryset(self.get_queryset())
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\filters.py", line 124, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1388, in build_filter
    return self._add_q(
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1292, in build_lookup
    raise FieldError(
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
[2022-12-11 20:23:50,224] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /modules/?search=%E9%A1%B9%E7%9B%AEx 500 [0.63, 127.0.0.1:51645]
[2022-12-11 20:23:51,207] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 20:23:51,209] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:51645]
[2022-12-11 20:26:35,291] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:26:38,185] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:26:38,185] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:26:38,185] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:27:26,331] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:27:28,817] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:27:28,817] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:27:28,817] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:27:36,603] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.12, 127.0.0.1:51870]
[2022-12-11 20:27:41,736] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:51882]
[2022-12-11 20:28:09,396] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:51902]
[2022-12-11 20:28:14,535] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:51909]
[2022-12-11 20:28:24,395] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search=%E9%A1%B9%E7%9B%AEx 200 [0.63, 127.0.0.1:51919]
[2022-12-11 20:28:25,023] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 20:28:25,024] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.19, 127.0.0.1:51919]
[2022-12-11 20:29:02,014] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:51945]
[2022-12-11 20:29:07,168] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search=x 200 [0.02, 127.0.0.1:51954]
[2022-12-11 20:29:11,199] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search= 200 [0.08, 127.0.0.1:51960]
[2022-12-11 20:29:15,055] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search=1 200 [0.05, 127.0.0.1:51970]
[2022-12-11 20:29:17,872] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search= 200 [0.06, 127.0.0.1:51973]
[2022-12-11 20:29:21,184] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search=sd 200 [0.12, 127.0.0.1:51979]
[2022-12-11 20:29:24,014] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?search= 200 [0.05, 127.0.0.1:51982]
[2022-12-11 20:29:26,750] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:51990]
[2022-12-11 20:30:13,973] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:52018]
[2022-12-11 20:30:18,496] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:52028]
[2022-12-11 20:30:20,883] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:52034]
[2022-12-11 20:30:22,982] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:52037]
[2022-12-11 20:31:28,001] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:52070]
[2022-12-11 20:31:30,080] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.08, 127.0.0.1:52076]
[2022-12-11 20:31:31,638] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.03, 127.0.0.1:52080]
[2022-12-11 20:31:33,823] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.06, 127.0.0.1:52087]
[2022-12-11 20:31:34,081] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:52091]
[2022-12-11 20:31:41,805] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52098]
[2022-12-11 20:31:44,896] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.09, 127.0.0.1:52107]
[2022-12-11 20:31:47,048] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.03, 127.0.0.1:52110]
[2022-12-11 20:31:48,856] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:52117]
[2022-12-11 20:31:52,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.07, 127.0.0.1:52126]
[2022-12-11 20:31:56,424] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.09, 127.0.0.1:52135]
[2022-12-11 20:31:58,038] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.11, 127.0.0.1:52138]
[2022-12-11 20:32:00,116] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.08, 127.0.0.1:52143]
[2022-12-11 20:32:05,797] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.07, 127.0.0.1:52151]
[2022-12-11 20:32:07,610] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.03, 127.0.0.1:52154]
[2022-12-11 20:32:09,801] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.09, 127.0.0.1:52160]
[2022-12-11 20:32:11,766] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.06, 127.0.0.1:52163]
[2022-12-11 20:32:16,760] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.06, 127.0.0.1:52172]
[2022-12-11 20:32:18,404] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.07, 127.0.0.1:52175]
[2022-12-11 20:32:22,612] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.11, 127.0.0.1:52181]
[2022-12-11 20:32:27,745] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.05, 127.0.0.1:52190]
[2022-12-11 20:32:30,822] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.07, 127.0.0.1:52197]
[2022-12-11 20:32:33,099] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /modules/ 200 [0.03, 127.0.0.1:52201]
[2022-12-11 20:32:35,357] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:52207]
[2022-12-11 20:32:39,142] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.09, 127.0.0.1:52211]
[2022-12-11 20:32:45,140] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.10, 127.0.0.1:52222]
[2022-12-11 20:33:09,796] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.05, 127.0.0.1:52238]
[2022-12-11 20:33:13,385] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.09, 127.0.0.1:52242]
[2022-12-11 20:33:18,544] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.03, 127.0.0.1:52249]
[2022-12-11 20:33:22,881] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?size=50 200 [0.11, 127.0.0.1:52258]
[2022-12-11 20:33:26,388] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?size=10 200 [0.09, 127.0.0.1:52267]
[2022-12-11 20:33:30,604] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?size=10&page=2 200 [0.06, 127.0.0.1:52274]
[2022-12-11 20:33:32,874] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?size=200 200 [0.13, 127.0.0.1:52278]
[2022-12-11 20:33:33,137] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?size=200&page=1 200 [0.07, 127.0.0.1:52282]
[2022-12-11 20:33:39,879] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52289]
[2022-12-11 20:33:40,359] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.06, 127.0.0.1:52293]
[2022-12-11 20:33:57,197] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.04, 127.0.0.1:52308]
[2022-12-11 20:34:13,637] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:52320]
[2022-12-11 20:34:23,168] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.07, 127.0.0.1:52330]
[2022-12-11 20:34:23,720] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.08, 127.0.0.1:52334]
[2022-12-11 20:34:25,471] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.03, 127.0.0.1:52339]
[2022-12-11 20:34:27,216] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.07, 127.0.0.1:52342]
[2022-12-11 20:34:37,885] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /projects/ 200 [0.09, 127.0.0.1:52353]
[2022-12-11 20:34:38,583] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.09, 127.0.0.1:52356]
[2022-12-11 20:34:48,827] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.06, 127.0.0.1:52367]
[2022-12-11 20:34:52,794] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=1 200 [0.08, 127.0.0.1:52377]
[2022-12-11 20:35:00,008] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/?page=2 200 [0.05, 127.0.0.1:52384]
[2022-12-11 20:41:22,961] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-11 20:41:26,240] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:41:26,646] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:41:26,646] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:41:26,646] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:50:11,283] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 20:50:14,310] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:50:14,746] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:50:14,746] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:50:14,746] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:52:34,517] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 20:52:37,691] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:52:38,081] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:52:38,081] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:52:38,081] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:53:43,427] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\models.py changed, reloading.
[2022-12-11 20:53:46,391] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:53:46,906] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:53:46,906] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:53:46,906] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:55:04,354] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 20:55:07,303] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:55:07,755] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:55:07,755] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:55:07,771] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:55:25,704] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 20:55:26,094] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 20:55:26,094] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 20:55:26,094] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 20:55:39,750] [runserver.py:153] [runserver:log_action] [INFO]- HTTP GET /cases 301 [0.02, 127.0.0.1:52735]
[2022-12-11 20:55:40,010] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.22, 127.0.0.1:52735]
[2022-12-11 20:55:40,390] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 20:55:40,392] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:52735]
[2022-12-11 20:56:47,864] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /modules/ 200 [0.16, 127.0.0.1:52759]
[2022-12-11 20:56:48,271] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 20:56:48,273] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.03, 127.0.0.1:52759]
[2022-12-11 21:00:33,828] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 21:00:37,045] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:01:25,579] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 21:01:29,541] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:01:30,057] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:01:30,058] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:01:30,060] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:02:58,475] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 21:03:01,420] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:04:14,641] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 21:04:17,613] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:05:31,423] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\serializer.py changed, reloading.
[2022-12-11 21:05:34,567] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:07:05,310] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:07:05,747] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:07:05,747] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:07:05,747] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:07:24,111] [log.py:241] [log:log_response] [WARNING]- Not Found: /modules/jquery.min.js
[2022-12-11 21:07:24,112] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /modules/jquery.min.js 404 [0.04, 127.0.0.1:53355]
[2022-12-11 21:07:25,522] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /cases/ 200 [0.63, 127.0.0.1:53355]
[2022-12-11 21:07:25,771] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:07:25,774] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53355]
[2022-12-11 21:07:34,830] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 526, in get
    mod['module'] = mod.name
TypeError: 'Module' object does not support item assignment
[2022-12-11 21:07:34,840] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [0.41, 127.0.0.1:53358]
[2022-12-11 21:07:35,022] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:07:35,023] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53358]
[2022-12-11 21:09:37,929] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 21:09:41,293] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:09:41,743] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:09:41,744] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:09:41,746] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:09:42,852] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 519, in get
    pro = Project.objects.get(id=mod['project'])
UnboundLocalError: local variable 'mod' referenced before assignment
[2022-12-11 21:09:42,867] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [0.50, 127.0.0.1:53438]
[2022-12-11 21:09:43,099] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:09:43,101] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.06, 127.0.0.1:53438]
[2022-12-11 21:10:07,104] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 21:10:10,415] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:10:10,898] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:10:10,898] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:10:10,898] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:10:12,141] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 531, in get
    case_relate = casenew.objects.get(id=case['related'])
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 636, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "D:\pythonList\web_python310\lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got [].
[2022-12-11 21:10:12,162] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [0.44, 127.0.0.1:53473]
[2022-12-11 21:10:12,596] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:10:12,598] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53473]
[2022-12-11 21:11:24,820] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 21:11:27,705] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:11:45,500] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 21:11:49,707] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:11:50,244] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:11:50,244] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:11:50,260] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:11:52,080] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py", line 531, in get
    case_relate = casenew.objects.get(id=case['related'].id)
AttributeError: 'list' object has no attribute 'id'
[2022-12-11 21:11:52,095] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [0.41, 127.0.0.1:53539]
[2022-12-11 21:11:53,837] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:11:53,839] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.11, 127.0.0.1:53544]
[2022-12-11 21:12:19,480] [autoreload.py:266] [autoreload:trigger_reload] [INFO]- C:\Users\Administrator\Desktop\myweb\myweb\saas\views.py changed, reloading.
[2022-12-11 21:12:22,585] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:12:23,477] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:12:23,478] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:12:23,479] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:12:24,536] [log.py:241] [log:log_response] [ERROR]- Internal Server Error: /cases/
Traceback (most recent call last):
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
  File "D:\pythonList\web_python310\lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 435, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "D:\Python310\lib\asyncio\tasks.py", line 408, in wait_for
    return await fut
  File "D:\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\asgiref\sync.py", line 476, in thread_handler
    return func(*args, **kwargs)
  File "D:\pythonList\web_python310\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 679, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 412, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\renderers.py", line 99, in render
    ret = json.dumps(
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "D:\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Python310\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "D:\Python310\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "D:\Python310\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "D:\Python310\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "D:\pythonList\web_python310\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "D:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Module is not JSON serializable
[2022-12-11 21:12:24,598] [runserver.py:160] [runserver:log_action] [ERROR]- HTTP GET /cases/ 500 [1.06, 127.0.0.1:53572]
[2022-12-11 21:12:25,896] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:12:25,898] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53572]
[2022-12-11 21:14:34,188] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:14:35,342] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:14:35,358] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:14:35,358] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:20:07,629] [autoreload.py:677] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2022-12-11 21:20:08,068] [server.py:111] [server:run] [INFO]- HTTP/2 support enabled
[2022-12-11 21:20:08,068] [server.py:122] [server:run] [INFO]- Configuring endpoint tcp:port=8000:interface=127.0.0.1
[2022-12-11 21:20:08,068] [server.py:153] [server:listen_success] [INFO]- Listening on TCP address 127.0.0.1:8000
[2022-12-11 21:20:13,594] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /cases/ 200 [0.30, 127.0.0.1:53837]
[2022-12-11 21:20:15,002] [log.py:241] [log:log_response] [WARNING]- Not Found: /cases/jquery.min.js
[2022-12-11 21:20:15,003] [runserver.py:155] [runserver:log_action] [WARNING]- HTTP GET /cases/jquery.min.js 404 [0.04, 127.0.0.1:53837]
